---
title: "Reportes para sala situacional y publicacion cientifica-Observatorio de Salud Intercultural"
---

Bienvenido al repositorio de reportes din谩micos del Observatorio. Aqu铆 encontrar谩 an谩lisis actualizados sobre producci贸n cient铆fica, bibliometr铆a y tendencias de investigaci贸n.

### Reportes Disponibles

::::: grid
::: g-col-6
###  [An谩lisis Bibliom茅trico Medicina Complementaria](Produccion_cientifica_mc.html)

**Fecha:** Diciembre 2025 **Datos:** Scopus (General) Un an谩lisis completo de la producci贸n cient铆fica global en Medicina Complementaria, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
### И [Producci贸n Cient铆fica Medicina Tradicional](Produccion_cientifica_mt.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global en Medicina Tradicional, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
### И [Producci贸n Cient铆fica Interculturalidad en Salud](Produccion_cientifica_interculturalidad.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global en interculturalidad en salud, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
### ┖ [Producci贸n Cient铆fica Determinantes sociales de la salud](Produccion_cientifica_determinantes.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global en determinantes sociales de la salud, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
###  [Producci贸n Cient铆fica peruana en Etnicidad en Salud](Produccion_cientifica_etnicidad.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global sobre desenlaces en salud en diferentes grupos 茅tnicos, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
###  [Producci贸n Cient铆fica peruana en promoci贸n de estilos de vida saludables](Produccion_cientifica_promocion.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global sobre la promoci贸n de estilos de vida saludables en poblaci贸n peruana, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::

::: {.g-col-6}
### ┖ [Producci贸n Cient铆fica peruana en Acceso a la Salud](Produccion_cientifica_acceso.html)
**Fecha:** Diciembre 2025
**Datos:** Scopus 
Un an谩lisis completo de la producci贸n cient铆fica global sobre acceso a la salud en poblaci贸n peruana, incluyendo tendencias temporales, mapas de colaboraci贸n y nubes de palabras clave.
:::
:::::
